/* features.js – extended Word-style features for OfflineWord (offline) */
(()=>{const $=s=>document.querySelector(s),pg=document.querySelector('#page'),B=document.body;
const dlg=document.createElement('dialog');dlg.id='askd';dlg.innerHTML='<form method="dialog"><b id="askq"></b><div id="aski"></div><div id="asko" style="display:grid;grid-template-columns:repeat(2,1fr);gap:4px;margin-top:6px"></div><div style="display:flex;flex-direction:row-reverse;gap:6px;margin-top:10px"><button value="ok" id="askok" style="background:#2b579a;color:#fff">OK</button><button value="c" id="askc">Cancel</button></div></form>';B.appendChild(dlg);
let pr=null,keep=null;const cap=()=>{const g=getSelection();return g.rangeCount&&pg.contains(g.anchorNode)?g.getRangeAt(0).cloneRange():(range?range.cloneRange():null)};const rk=()=>{if(keep)range=keep.cloneRange()};
window.ask=(q,d='',multi)=>new Promise(r=>{$('#askq').textContent=q;$('#asko').innerHTML='';$('#askok').style.display='';const i=document.createElement(multi?'textarea':'input');i.id='askin';i.value=d;if(multi)i.rows=8;i.style.cssText='width:100%;margin-top:6px;border:1px solid #cfd3d9';$('#aski').replaceChildren(i);dlg.onclose=()=>{rk();r(dlg.returnValue==='ok'?i.value:null)};dlg.showModal();i.focus()});
const pick=(q,items)=>new Promise(r=>{$('#askq').textContent=q;$('#aski').innerHTML='';$('#askok').style.display='none';const o=$('#asko');o.innerHTML='';pr=null;items.forEach(k=>{const b=document.createElement('button');b.type='button';b.textContent=k;b.style.cssText='border:1px solid #cfd3d9;height:auto;padding:6px';b.onclick=()=>{pr=k;dlg.close('x')};o.appendChild(b)});dlg.onclose=()=>{rk();r(pr)};dlg.showModal()});
const st=document.createElement('style');st.textContent=`#page.marks :is(p,h1,h2,h3,h4,h5,h6,li)::after{content:" ¶";color:#6a8bd1}#page.ln{counter-reset:ln}#page.ln>:is(p,h1,h2,h3,li){position:relative}#page.ln>:is(p,h1,h2,h3)::before{counter-increment:ln;content:counter(ln);position:absolute;left:-40px;color:#999;font-size:11px}#page.grid{background-image:linear-gradient(#0001 1px,transparent 1px);background-size:100% 24px}#page.web{width:100%!important;box-shadow:none}#page::before{content:attr(data-h);position:absolute;top:30px;left:0;right:0;text-align:center;color:#888;font-size:12px}#page::after{content:attr(data-f);position:absolute;bottom:30px;left:0;right:0;text-align:center;color:#888;font-size:12px}body.rd #top,body.rd #bar,body.rd #bar2,body.fc #top,body.fc #bar,body.fc #bar2,body.fc #status{display:none}body.dr #page img,body.dr .obj{display:none}body.np #wrap{margin-left:220px}#navp{position:fixed;left:0;top:90px;bottom:24px;width:220px;background:#fff;border-right:1px solid #cfd3d9;overflow:auto;padding:8px;z-index:5}#navp a{display:block;padding:3px;cursor:pointer}#bar2 button.m{background:#e9eef7}.cmt{background:#fff3a0}`;document.head.appendChild(st);
const ps=document.createElement('style');document.head.appendChild(ps);
const S=JSON.parse(localStorage.getItem('offlineword.pg')||'null')||{w:794,h:1123,pn:0,pad:96,cols:1};
const E=s=>String(s).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;');
function pgApply(){pg.style.width=S.w+'px';pg.style.minHeight=S.h+'px';pg.style.padding=S.pad+'px';pg.style.columnCount=S.cols;if(S.bg)pg.style.backgroundColor=S.bg;if(S.wm)pg.style.backgroundImage=`url("data:image/svg+xml,${encodeURIComponent(S.wm)}")`;else pg.style.backgroundImage='';pg.dataset.h=S.hdr||'';pg.dataset.f=S.ftr||'';pg.style.outline=S.bd?'2px solid #333':'';
 ps.textContent=`@page{size:${S.w}px ${S.h}px;margin:20mm;${S.hdr?`@top-center{content:"${(S.hdr+'').replace(/"/g,'')}"}`:''}${S.pn||S.ftr?`@bottom-center{content:${S.ftr?`"${(S.ftr+'').replace(/"/g,'')} "`:''}${S.pn?'counter(page)':''}}`:''}}`;localStorage.setItem('offlineword.pg',JSON.stringify(S));try{setZoom(zoom)}catch(e){}}
pgApply();
const cmd=(c,v)=>{restore();document.execCommand(c,false,v);store()};
const sel=()=>range?range.toString():'';
const wrap=async s=>{const r=range;if(!r||r.collapsed)return alert('Select some text first');const e=document.createElement('span');e.style.cssText=s;e.appendChild(r.extractContents());r.insertNode(e);store()};
const bs=o=>{blocksInRange().forEach(b=>Object.assign(b.style,o));store()};
const ins=h=>cmd('insertHTML',h);
const insB=h=>{restore();const g=getSelection(),r=g.rangeCount?g.getRangeAt(0):range,t=document.createElement('template');t.innerHTML=h;const b=blk(r.startContainer);if(b&&b!==pg)b.after(t.content);else pg.appendChild(t.content);store()};
const cell=()=>{const n=range&&range.startContainer,e=n&&(n.nodeType==1?n:n.parentElement);return e&&e.closest&&e.closest('td,th')};
const need=f=>{const c=cell();if(!c)return alert('Click inside a table cell first');f(c,c.parentElement,c.closest('table'))};
let img=null;pg.addEventListener('click',e=>{img=e.target.tagName==='IMG'?e.target:null});
const needImg=f=>img?(f(img),store()):alert('Click a picture first');
const heads=()=>[...pg.querySelectorAll('h1,h2,h3,h4,h5,h6')].filter(h=>!h.closest('[data-toc]'));
const toc=()=>{const hs=heads();hs.forEach(h=>h.id||(h.id='h'+Math.random().toString(36).slice(2,7)));return `<div data-toc="1"><b>Table of Contents</b>${hs.map(h=>`<p style="margin:0 0 0 ${(+h.nodeName[1]-1)*20}px"><a href="#${h.id}">${E(h.textContent)}</a></p>`).join('')}</div><p><br></p>`};
const note=async(c)=>{const t=await ask('Note text');if(!t)return;const n=pg.querySelectorAll('sup.'+c).length+1;ins(`<sup class="${c}">${c=='en'?['i','ii','iii','iv','v','vi','vii','viii','ix','x'][n-1]||n:n}</sup>`);if(!pg.querySelector('hr.fnh'))pg.insertAdjacentHTML('beforeend','<hr class="fnh">');pg.insertAdjacentHTML('beforeend',`<p class="fnt" style="font-size:12px"><sup>${c=='en'?'e':''}${n}</sup> ${E(t)}</p>`);store()};
const ver=()=>JSON.parse(localStorage.getItem('offlineword.ver')||'[]');
const snap=()=>{const v=ver();v.push({t:new Date().toLocaleString(),h:pg.innerHTML});localStorage.setItem('offlineword.ver',JSON.stringify(v.slice(-15)))};
const lst=(k)=>async()=>{const o={Bullet:['disc','circle','square'],Number:['decimal','lower-alpha','upper-alpha','lower-roman','upper-roman']}[k],v=await pick(k+' style',o);if(!v)return;restore();const n=range&&(range.startContainer.nodeType==1?range.startContainer:range.startContainer.parentElement),l=n&&n.closest('ul,ol');if(l){l.style.listStyleType=v;store()}else alert('Put the cursor in a list first')};
const exitModes=()=>{B.classList.remove('rd','fc');pg.contentEditable='true'};
addEventListener('keydown',e=>{if(e.key==='Escape')exitModes()});
let fp=null;pg.addEventListener('mouseup',()=>{if(fp&&range&&!range.collapsed){const f=fp;fp=null;wrap(f)}});
const M={
Text:{'Change case (cycle)':()=>{const t=sel();if(!t)return;const u=t.toUpperCase(),l=t.toLowerCase();cmd('insertText',t===u?l:t===l?t.replace(/\b\w/g,c=>c.toUpperCase()):u)},'Clear all formatting':()=>{cmd('removeFormat');cmd('unlink')},'Grow font':()=>{restore();cmd('fontSize',Math.min(7,+(document.queryCommandValue('fontSize')||3)+1))},'Shrink font':()=>{restore();cmd('fontSize',Math.max(1,+(document.queryCommandValue('fontSize')||3)-1))},'Format painter':()=>{const n=getSelection().anchorNode,e=n&&(n.nodeType==1?n:n.parentElement);if(!e)return;const c=getComputedStyle(e);fp=`font-family:${c.fontFamily};font-size:${c.fontSize};font-weight:${c.fontWeight};font-style:${c.fontStyle};color:${c.color};text-decoration:${c.textDecorationLine}`;$('#saved').textContent='Painter on: select text to apply'},'Small caps':()=>wrap('font-variant:small-caps'),'ALL CAPS':()=>wrap('text-transform:uppercase'),'Character spacing…':async()=>{const v=await ask('Spacing in px (e.g. 2, -1)','2');if(v)wrap(`letter-spacing:${+v}px`)},'Text scale %…':async()=>{const v=await ask('Scale %','150');if(v)wrap(`display:inline-block;transform:scaleX(${v/100});transform-origin:left`)},'Shadow':()=>wrap('text-shadow:2px 2px 3px #0008'),'Glow':()=>wrap('text-shadow:0 0 8px #4af,0 0 2px #4af'),'Outline text':()=>wrap('color:transparent;-webkit-text-stroke:1px #000'),'Double strikethrough':()=>wrap('text-decoration:line-through double'),'Text border':()=>wrap('border:1px solid #000;padding:0 3px'),'Shading…':async()=>{const v=await ask('Colour (hex)','#ffd966');if(v)wrap('background:'+v)},'Ligatures':()=>wrap('font-variant-ligatures:common-ligatures'),'Tabular numbers':()=>wrap('font-variant-numeric:tabular-nums lining-nums'),'Old-style numbers':()=>wrap('font-variant-numeric:oldstyle-nums'),'Vertical text':()=>bs({writingMode:'vertical-rl'}),'Drop cap':()=>{const b=blocksInRange()[0];if(b&&b.firstChild){const t=b.textContent;b.innerHTML=`<span style="float:left;font-size:3.2em;line-height:.85;padding-right:6px">${E(t[0])}</span>${E(t.slice(1))}`;store()}}},
Paragraph:{'Bullet style…':lst('Bullet'),'Number style…':lst('Number'),'Restart numbering':()=>{const n=range&&range.startContainer,e=n&&(n.nodeType==1?n:n.parentElement),l=e&&e.closest('ol');if(l){l.start=1;store()}},'Hanging indent':()=>bs({marginLeft:'40px',textIndent:'-40px'}),'First-line indent':()=>bs({textIndent:'40px'}),'Keep with next':()=>bs({breakAfter:'avoid'}),'Keep lines together':()=>bs({breakInside:'avoid'}),'Page break before':()=>bs({breakBefore:'page'}),'Right-to-left':()=>bs({direction:'rtl',textAlign:'right'}),'Left-to-right':()=>bs({direction:'ltr',textAlign:'left'}),'Paragraph border':()=>bs({border:'1px solid #000',padding:'4px'}),'Paragraph shading…':async()=>{const v=await ask('Colour (hex)','#e8eefc');if(v)bs({background:v})},'Insert tab stop':()=>ins('&emsp;&emsp;'),'Sort A→Z':()=>srt(1),'Sort Z→A':()=>srt(-1),'Show/hide ¶ marks':()=>pg.classList.toggle('marks')},
Layout:{'Margins…':async()=>{const v=await pick('Margins',['Normal','Narrow','Wide']);if(v){S.pad={Normal:96,Narrow:48,Wide:144}[v];pgApply()}},'Orientation…':async()=>{const v=await pick('Orientation',['Portrait','Landscape']);if(v){const a=Math.min(S.w,S.h),b=Math.max(S.w,S.h);S.w=v=='Portrait'?a:b;S.h=v=='Portrait'?b:a;pgApply()}},'Paper size…':async()=>{const v=await pick('Paper',['A4','A5','Letter','Legal']);if(v){const d={A4:[794,1123],A5:[559,794],Letter:[816,1056],Legal:[816,1344]}[v];S.w=d[0];S.h=d[1];pgApply()}},'Columns…':async()=>{const v=await pick('Columns',['1','2','3']);if(v){S.cols=+v;pgApply()}},'Page break':()=>insB('<div style="break-after:page;border-top:1px dashed #aaa"></div><p><br></p>'),'Section break':()=>insB('<div style="break-after:page;border-top:2px dashed #2b579a"></div><p><br></p>'),'Page colour…':async()=>{const v=await ask('Colour (hex)','#fffbe6');if(v){S.bg=v;pgApply()}},'Page border':()=>{S.bd=!S.bd;pgApply()},'Watermark…':async()=>{const v=await ask('Watermark text (empty = remove)','DRAFT');S.wm=v?`<svg xmlns="http://www.w3.org/2000/svg" width="500" height="500"><text x="250" y="270" font-size="90" fill="#0002" text-anchor="middle" transform="rotate(-35 250 250)" font-family="Arial">${E(v)}</text></svg>`:'';pgApply()},'Header…':async()=>{const v=await ask('Header text',S.hdr||'');if(v!==null){S.hdr=v;pgApply()}},'Footer…':async()=>{const v=await ask('Footer text',S.ftr||'');if(v!==null){S.ftr=v;pgApply()}},'Page numbers on/off':()=>{S.pn=!S.pn;pgApply()},'Line numbers':()=>pg.classList.toggle('ln'),'Gridlines':()=>pg.classList.toggle('grid'),'Hyphenation':()=>{pg.lang='en';pg.style.hyphens=pg.style.hyphens?'':'auto'}},
Insert:{'Hyperlink…':async()=>{const v=await ask('URL','https://');if(v)cmd('createLink',v)},'Remove link':()=>cmd('unlink'),'Date & time':()=>cmd('insertText',new Date().toLocaleString()),'Symbol…':async()=>{const v=await pick('Symbol',[...'©®™€£¥§°±×÷≠≤≥∞πΩ→←↑↓✓★☎✉♥α β γ Δ Σ µ'.replace(/ /g,'')]);if(v)cmd('insertText',v)},'Equation…':async()=>{const v=await ask('Equation text (use ^ for powers, _ for subscripts)','x^2 + y^2 = z^2');if(v)ins('<i>'+E(v).replace(/\^(\w+)/g,'<sup>$1</sup>').replace(/_(\w+)/g,'<sub>$1</sub>')+'</i>')},'WordArt…':async()=>{const v=await ask('Text','WordArt');if(v)ins(`<span style="font:bold 44px Arial;background:linear-gradient(90deg,#e33,#fa0,#36f);-webkit-background-clip:text;color:transparent">${E(v)}</span>`)},'Chart…':async()=>{const v=await ask('Values, comma-separated','5,9,3,7');if(!v)return;const a=v.split(',').map(Number),m=Math.max(...a);insB(`<svg width="${a.length*50+20}" height="150" style="border:1px solid #ccc">${a.map((x,i)=>`<rect x="${15+i*50}" y="${130-x/m*110}" width="36" height="${x/m*110}" fill="#4472c4"/><text x="${33+i*50}" y="${125-x/m*110}" font-size="11" text-anchor="middle">${x}</text>`).join('')}</svg>`)},'Signature line':()=>insB('<p>______________________________<br>Signature &nbsp;&nbsp; Date: ____________</p>'),'Bookmark…':async()=>{const v=await ask('Bookmark name');if(v)ins(`<span id="bm_${v.replace(/\W/g,'')}" data-bm="${E(v)}">\u200b</span>`)},'Cross-reference…':async()=>{const b=[...pg.querySelectorAll('[data-bm]')].map(x=>x.dataset.bm);if(!b.length)return alert('No bookmarks yet');const v=await pick('Link to',b);if(v)ins(`<a href="#bm_${v.replace(/\W/g,'')}">${E(v)}</a>`)},'Comment…':async()=>{const v=await ask('Comment');if(v)wrap('background:#fff3a0').then(()=>{const l=pg.querySelectorAll('span[style*="fff3a0"],span[style*="255, 243, 160"]');const e=l[l.length-1];if(e)e.title='Comment: '+v})},'Picture alt text…':()=>needImg(async i=>{const v=await ask('Alt text',i.alt);if(v!==null)i.alt=v}),'Picture brightness/contrast…':()=>needImg(async i=>{const v=await ask('Brightness %, Contrast % (e.g. 120,110)','100,100');if(v){const[a,b]=v.split(',');i.style.filter=`brightness(${a}%) contrast(${b||100}%)`}}),'Picture rotate…':()=>needImg(async i=>{const v=await ask('Degrees','90');if(v)i.style.transform=`rotate(${v}deg)`}),'Picture flip':()=>needImg(i=>i.style.transform=(i.style.transform||'')+' scaleX(-1)'),'Picture size %…':()=>needImg(async i=>{const v=await ask('Width % of page','50');if(v)i.style.width=v+'%'}),'Picture border':()=>needImg(i=>i.style.border='2px solid #333'),'Picture wrap left':()=>needImg(i=>{i.style.float='left';i.style.margin='4px 12px 4px 0'}),'Picture wrap right':()=>needImg(i=>{i.style.float='right';i.style.margin='4px 0 4px 12px'}),'Picture inline':()=>needImg(i=>{i.style.float='';i.style.margin=''}),'Bring forward':()=>zi(1),'Send backward':()=>zi(-1),'Delete selected object':()=>{if(selObj){selObj.remove();selObj=null;store()}}},
Table:{'Row above':()=>need((c,r)=>r.before(mk(r))),'Row below':()=>need((c,r)=>r.after(mk(r))),'Column left':()=>need((c,r,t)=>[...t.rows].forEach(x=>x.insertCell(c.cellIndex).innerHTML='<br>')),'Column right':()=>need((c,r,t)=>[...t.rows].forEach(x=>x.insertCell(c.cellIndex+1).innerHTML='<br>')),'Delete row':()=>need((c,r)=>r.remove()),'Delete column':()=>need((c,r,t)=>{const i=c.cellIndex;[...t.rows].forEach(x=>x.deleteCell(i))}),'Delete table':()=>need((c,r,t)=>t.remove()),'Merge with right cell':()=>need(c=>{const n=c.nextElementSibling;if(n){c.colSpan+=n.colSpan;c.innerHTML+=' '+n.innerHTML;n.remove()}}),'Split cell':()=>need((c,r)=>{if(c.colSpan>1)c.colSpan--;r.insertCell(c.cellIndex+1).innerHTML='<br>'}),'Cell alignment…':async()=>{const v=await pick('Align',['left','center','right','top','middle','bottom']);if(v)need(c=>{if(/left|center|right/.test(v))c.style.textAlign=v;else c.style.verticalAlign=v})},'Table style…':async()=>{const v=await pick('Style',['Grid','Banded','Header colour','Plain']);if(v)need((c,r,t)=>{t.querySelectorAll('td,th').forEach(x=>{x.style.border=v=='Plain'?'0':'1px solid #444';x.style.background=''});if(v=='Banded')[...t.rows].forEach((x,i)=>i%2&&[...x.cells].forEach(d=>d.style.background='#eef3fb'));if(v=='Header colour')[...t.rows[0].cells].forEach(d=>{d.style.background='#2b579a';d.style.color='#fff'})})},'AutoFit to window':()=>need((c,r,t)=>t.style.width='100%'),'Repeat header row':()=>need((c,r,t)=>{const h=t.tBodies[0]?t.rows[0]:null;if(h){const th=t.createTHead();th.appendChild(h)}}),'Sum of cells above':()=>need((c,r,t)=>{let s=0;for(const x of t.rows){if(x===r)break;s+=parseFloat(x.cells[c.cellIndex]?.textContent)||0}c.textContent=s}),'Text → table':()=>{const t=sel();if(!t)return alert('Select text lines (tab or comma separated)');ins('<table>'+t.split('\n').filter(x=>x.trim()).map(l=>'<tr>'+l.split(/\t|,/).map(c=>`<td>${E(c)}</td>`).join('')+'</tr>').join('')+'</table><p><br></p>')},'Table → text':()=>need((c,r,t)=>{t.outerHTML=[...t.rows].map(x=>'<p>'+[...x.cells].map(d=>E(d.textContent)).join('&emsp;')+'</p>').join('');store()})},
References:{'Table of contents':()=>insB(toc()),'Update table of contents':()=>{const t=pg.querySelector('[data-toc]');if(t){t.outerHTML=toc().replace('<p><br></p>','');store()}else insB(toc())},'Footnote…':()=>note('fn'),'Endnote…':()=>note('en'),'Caption…':async()=>{const v=await ask('Caption text');if(v){const n=pg.querySelectorAll('.cap').length+1;ins(`<p class="cap" style="text-align:center;font-style:italic">Figure ${n}: ${E(v)}</p>`)}},'Table of figures':()=>insB('<div><b>Table of Figures</b>'+[...pg.querySelectorAll('.cap')].map(c=>`<p style="margin:0">${E(c.textContent)}</p>`).join('')+'</div>'),'Index (headings A–Z)':()=>insB('<div><b>Index</b>'+heads().map(h=>h.textContent).sort((a,b)=>a.localeCompare(b)).map(t=>`<p style="margin:0">${E(t)}</p>`).join('')+'</div>')},
Review:{'Word count':()=>{const t=pg.innerText.trim(),w=t?t.split(/\s+/).length:0;alert(`Words: ${w}\nCharacters: ${t.length}\nParagraphs: ${pg.querySelectorAll('p,h1,h2,h3,h4,h5,h6,li').length}\nReading time: ${Math.max(1,Math.round(w/200))} min`)},'Read aloud':()=>{speechSynthesis.cancel();speechSynthesis.speak(new SpeechSynthesisUtterance(sel()||pg.innerText))},'Stop reading':()=>speechSynthesis.cancel(),'Spelling check on/off':()=>{pg.spellcheck=!pg.spellcheck},'Protect / unprotect (read-only)':()=>{pg.contentEditable=pg.contentEditable==='true'?'false':'true';$('#saved').textContent=pg.contentEditable==='true'?'Editing allowed':'Document locked (read-only)'},'Inspect document':()=>alert(`Pictures: ${pg.querySelectorAll('img').length} (without alt text: ${pg.querySelectorAll('img:not([alt]),img[alt=""]').length})\nTables: ${pg.querySelectorAll('table').length}\nComments: ${pg.querySelectorAll('[title^=Comment]').length}\nSize: ${Math.round(pg.innerHTML.length/1024)} KB`),'Save version snapshot':()=>{snap();$('#saved').textContent='Version saved'},'Version history…':async()=>{const v=ver();if(!v.length)return alert('No snapshots yet');const k=await pick('Restore version',v.map((x,i)=>i+1+'. '+x.t));if(k){snap();pg.innerHTML=v[parseInt(k)-1].h;store()}},'Share…':async()=>{try{const f=new File([DOCX.toBlob(pg)],($('#title').value||'Document')+'.docx');if(navigator.canShare&&navigator.canShare({files:[f]}))await navigator.share({files:[f]});else location.href='mailto:?subject='+encodeURIComponent($('#title').value)+'&body='+encodeURIComponent(pg.innerText.slice(0,1500))}catch(e){}}},
View:{'Read mode':()=>{B.classList.add('rd');pg.contentEditable='false'},'Focus mode':()=>B.classList.add('fc'),'Navigation pane':()=>{let n=$('#navp');if(n){B.classList.remove('np');return n.remove()}B.classList.add('np');n=document.createElement('div');n.id='navp';n.innerHTML='<b>Navigation</b>';heads().forEach(h=>{const a=document.createElement('a');a.textContent=h.textContent;a.style.paddingLeft=(+h.nodeName[1]*8)+'px';a.onclick=()=>h.scrollIntoView({behavior:'smooth'});n.appendChild(a)});if(!heads().length)n.innerHTML+='<p>No headings yet.</p>';B.appendChild(n);n.style.top=$('#bar2').getBoundingClientRect().bottom+'px'},'Draft view':()=>B.classList.toggle('dr'),'Web layout':()=>pg.classList.toggle('web'),'New window':()=>open(location.href),'Show/hide ¶ marks':()=>pg.classList.toggle('marks')},
Mailings:{'Mail merge…':async()=>{const d=await ask('Paste data: first row = field names (comma separated). Use {{Field}} in your document.','Name,City\nAnna,Paris\nBen,Rome',1);if(!d)return;const rows=d.trim().split('\n').map(r=>r.split(',').map(x=>x.trim())),h=rows.shift(),t=pg.innerHTML;snap();pg.innerHTML=rows.map(r=>h.reduce((s,f,i)=>s.split('{{'+f+'}}').join(E(r[i]||'')),t)).join('<div style="break-after:page"></div>');store()}}};
function mk(r){const n=document.createElement('tr');[...r.cells].forEach(()=>n.insertCell().innerHTML='<br>');return n}
function srt(d){const bl=blocksInRange().filter(b=>b.parentNode);if(bl.length<2)return;const t=bl.map(b=>b.cloneNode(true)).sort((a,b)=>d*a.textContent.localeCompare(b.textContent));bl.forEach((b,i)=>b.replaceWith(t[i]));store()}
function zi(d){if(selObj){selObj.style.zIndex=(+selObj.style.zIndex||1)+d;store()}else alert('Select a shape or text box first')}
const bar=document.createElement('div');bar.id='bar2';$('#bar').after(bar);
const add=(l,f,c)=>{const b=document.createElement('button');b.textContent=l;if(c)b.className='m';b.onmousedown=e=>e.preventDefault();b.onclick=()=>{keep=cap();f()};bar.appendChild(b)};
add('🔍 Find',async()=>{const v=await ask('Find');if(v)find(v)});add('Replace…',async()=>{const f=await ask('Find');if(f===null)return;const r=await ask('Replace with');if(r===null)return;let n=0;const w=document.createTreeWalker(pg,4);const ns=[];while(w.nextNode())ns.push(w.currentNode);ns.forEach(x=>{if(x.data.includes(f)){n+=x.data.split(f).length-1;x.data=x.data.split(f).join(r)}});store();alert(n+' replaced')});
add('Select all',()=>{restore();document.execCommand('selectAll')});
function find(v){pg.focus();getSelection().removeAllRanges();window.find(v,false,false,true)}
Object.keys(M).forEach(k=>add(k+' ▾',async()=>{const v=await pick(k,Object.keys(M[k]));if(v)try{await M[k][v]()}catch(e){alert(e.message)}},1));
})();
